# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle & Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]

    steps:
    # Checkout repo
    - uses: actions/checkout@v4.0.0

    # Set up Java
    - name: Set up JDK 8
      uses: actions/setup-java@v4.7.1
      with:
        distribution: temurin
        java-version: 8

    # Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build project
    - name: Build with Gradle
      run: ./gradlew build

    # Confirm JAR exists
    - name: List build/libs contents
      run: ls -l build/libs

    # Build & push Docker image
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: fela14/actions-demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  publish:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Placeholder
      run: echo "Publish job will go here"

